---

- hosts: spotlight

  vars_files:
    - vars.yml

  vars_prompt:
    name: command
    prompt: "Do you wish to [start] or [stop] the Spotlight server? (command)"
    private: no

  tasks:

    # Document commands
    - name: Start the Spotlight server
      command: rails server --binding=0.0.0.0 --daemon
      args:
        chdir: '{{ app_dir }}'
      when: command == 'start'

    - name: Get running Spotlight PID
      command: cat '{{ app_dir }}/tmp/pids/server.pid'
      register: spotlight_pid
      changed_when: false
      when: command == 'stop'

    - name: Stop the Spotlight server
      command: kill --signal=INT '{{ spotlight_pid.stdout }}'
      when: command == 'stop'
