---

- name: Deploys Exhibits App
  hosts: spotlight

  environment:
    DATABASE_URL: 'postgres://{{ app_db_user }}:{{ app_db_pass }}@{{ app_db_host }}:{{ app_db_port }}/{{ app_db_name }}'
    RAILS_ENV: '{{ rails_environment }}'
    SECRET_KEY_BASE: '{{ rails_secret_key }}'
    PATH: '{{ ansible_user_dir }}/.rbenv/shims:{{ ansible_user_dir }}/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'

  roles:
    -  { name: ansistrano.deploy }
