---

- name: Deploys Exhibits App
  hosts: spotlight

  roles:
    - name: ansistrano.deploy
      environment:
        DATABASE_URL: '{{ rails_database_url | default (omit) }}'
        PATH: '{{ ansible_user_dir }}/.rbenv/shims:{{ ansible_user_dir }}/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin'
        RAILS_ENV: '{{ rails_environment | default ("development") }}'
        RAILS_MASTER_KEY: '{{ rails_master_key | default (omit) }}'

  pre_tasks:
    - name: Install OS dependecies
      package:
        name: [ 'rsync', 'acl' ]
        state: present
      become: true
