---

- hosts: spotlight

  vars_files:
    - vars.yml

  roles:
    #- ucsdlib.java
    - { role: 'ucsdlib.solr', solr_version: '{{ solr_indexer_version }}', become: true }
    #- zzet.rbenv

  tasks:
    - name: 'Start Solr'
      service:
        name: solr
        state: running
        #use: service
      become: true

    - name: "Add Brightbox PPA (Ruby 2.2)"
      apt_repository:
        repo: 'ppa:brightbox/ruby-ng'
        state: present
      become: true

    - name: "Use Ruby 2.2"
      package:
        name: ruby2.2
        state: present
      become: true

    - name: "Install build deps"
      package:
        name: '{{ item }}'
        state: present
      become: true
      with_items:
        - ruby2.2-dev
        - zlib1g-dev
        - libsqlite3-dev
        - build-essential

    - name: "Install additional deps"
      package:
        name: '{{ item }}'
        state: present
      become: true
      with_items:
        - nodejs
        - git

    - name: "Install System Gems"
      gem:
        name: '{{ item.gem }}'
        version: '{{ item.version | default ("") }}'
        user_install: false
      become: true
      with_items:
        #- { gem: 'solr_wrapper' }
        - { gem: 'bundler', version: '{{ bundler_version }}' }
        - { gem: 'rails', version: '{{ rails_version }}' }

    - name: 'Create new rails application'
      command: 'rails new {{ app_dir }}'
      args:
          creates: '{{ app_dir }}'

    - name: 'Add Spotlight to Gemfile'
      lineinfile:
        dest: '{{ app_dir }}/Gemfile'
        line: '{{ item }}'
        state: present
      with_items:
        - 'gem "blacklight", "{{ blacklight_version }}"'
        - 'gem "blacklight-spotlight", "{{ spotlight_version }}"'

    - name: 'Update Bundle'
      command: 'bundle install'
      args:
        chdir: '{{ app_dir }}'
      register: bundle
      changed_when: '"Installing" in bundle.stdout'

    - name: 'Install Blacklight'
      command: 'rails generate blacklight:install {{ blacklight_options }}'
      args:
        chdir: '{{ app_dir }}'
        creates: 'config/blacklight.yml'

    - name: 'Install Spotlight'
      command: 'rails generate spotlight:install {{ spotlight_options }}'
      args:
        chdir: '{{ app_dir }}'
        creates: 'config/sitemap.rb'
      # Very uncomfortable with this creates flag

    - name: 'Update bundle, again'
      command: 'bundle install'
      args:
        chdir: '{{ app_dir }}'
      register: bundle
      changed_when: '"Installing" in bundle.stdout'

    - name: 'Migrate Blacklight to Spotlight'
      command: 'rake spotlight:install:migrations'
      args:
        chdir: '{{ app_dir }}'
        creates: db/schema.rb

    - name: 'Work around bugs'
      command: 'rails {{ item.command }}'
      args:
        chdir: '{{ app_dir }}'
        creates: '{{ item.creates }}'
      with_items:
        - { command: 'generate devise_invitable:install', creates: 'config/locales/devise_invitable.en.yml' }
        - { command: 'generate devise_invitable User',    creates: 'db/migrate/*_devise_invitable_add_to_users.rb' }

    - name: 'Initial database migrate'
      command: 'rake db:migrate'
      args:
        chdir: '{{ app_dir }}'
      register: rake_out
      changed_when: rake_out.stdout != ''

    - name: 'Create Solr Core'
      command: /opt/solr/bin/solr create -c {{ solr_core | default ("blacklight-core") }} -d solr/conf
      args:
         chdir: '{{ app_dir }}'
         creates: /var/solr/data/{{ solr_core | default ("blacklight-core") }}
      become: true
      become_user: solr
      tags:
         - solr_core
