---

- name: Install required runtime dependencies
  hosts: spotlight

  tasks:
    - name: Install distro packages
      package:
        name: '{{ item }}'
        state: present
      loop:
        - '{{ runtime_packages }}'
