---

- name: Resets pgsql db
  hosts: spotlight

  roles:
    - name: geerlingguy.postgresql
      become: true
      postgresql_databases:
        - name: spotlight_db
          state: absent

    - name: geerlingguy.postgresql
      become: true
