---

- hosts: spotlight

  tasks:
    - name: "Add /usr/local to sudo's path"
      lineinfile:
        dest: /etc/sudoers.d/securepath
        line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/sbin:/usr/local/bin'
        state: present
        create: yes
      when: false

    - name: "Set hostname"
      command: 'hostname {{ inventory_hostname }}'
      changed_when: false
      become: true
